name: learn-github-actions
on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Contextual QA Checklists
        uses: wyozi/contextual-qa-checklist-action@1.2

